services:
  terraform:
    image: hashicorp/terraform:1.6
    volumes:
      - .:/workspace
      - ../ansible/inventory:/ansible/inventory
    working_dir: /workspace

  init:
    image: hashicorp/terraform:1.6
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: [ "init" ]

  plan:
    image: hashicorp/terraform:1.6
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: [ "plan" ]

  apply:
    image: hashicorp/terraform:1.6
    volumes:
      - .:/workspace
      - ../ansible/inventory:/ansible/inventory
    working_dir: /workspace
    command: [ "apply", "-auto-approve" ]

  destroy:
    image: hashicorp/terraform:1.6
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: [ "destroy", "-auto-approve" ]
