- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-amd64.tar.gz
    dest: /home/{{ ansible_user }}/node_exporter-1.10.2.linux-amd64.tar.gz
    mode: '0644'

- name: Extract Node Exporter
  unarchive:
    src: /home/{{ ansible_user }}/node_exporter-1.10.2.linux-amd64.tar.gz
    dest: /home/{{ ansible_user }}/
    remote_src: yes

- name: Create Node Exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User={{ ansible_user }}
      Type=simple
      ExecStart=/home/{{ ansible_user }}/node_exporter-1.10.2.linux-amd64/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes

- name: Display Node Exporter access URL
  debug:
    msg: "Node Exporter is available at http://{{ ansible_host }}:9100/metrics"