---
# Main playbook that runs all playbooks in order

# Docker nodes setup
- name: Install Docker on Docker Nodes
  import_playbook: install-docker.yml

- name: Deploy Node Exporter on Docker Nodes
  import_playbook: deploy-monitoring.yml

- name: Deploy Project on Docker Nodes
  import_playbook: deploy-project.yml

# Monitor node setup
- name: Deploy Prometheus and Grafana on Monitor Node
  import_playbook: deploy-prometheus.yml
