---
# Main playbook that runs all playbooks in order

# Docker nodes setup
- import_playbook: base-package-setup.yml

- import_playbook: node-exporter-deploy.yml

- import_playbook: blackbox-deploy.yml

- import_playbook: prometheus-deploy.yml

- import_playbook: grafana-deploy.yml

- import_playbook: project-deploy.yml

# - name: Deploy Project on Docker Nodes
#   import_playbook: deploy-project.yml