- name: Setup Base Packages
  hosts: all
  become: true
  roles:
    - role: base
      tags: base

- name: Deploy Monitoring Stack
  hosts: monitor
  become: true
  vars_files:
    - group_vars/vault.yml
  roles:
    - role: monitor/prometheus
      tags:
        - prometheus
        - monitoring
    - role: monitor/grafana
      tags: 
        - grafana
        - monitoring

- name: Deploy Node Exporter
  hosts: docker_nodes
  become: true
  roles:
    - role: monitor/node_exporter
      tags:
        - node_exporter
        - monitoring