dependencies:
  - role: prometheus,
    tags:
      - prometheus
      - monitoring
  - role: grafana,
    tags:
      - grafana
      - monitoring
      - alerting
  - role: node_exporter,
    tags:
      - node_exporter
      - monitoring